lesson6_home_work/lesson6_home_work/urls.py
import debug_toolbar
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
from core import views as core_view
from api import views as api_view
from rest_framework.authtoken.views import obtain_auth_token

urlpatterns = [
    path('', core_view.IndexView.as_view(), name='index'),
    path('csv/', core_view.StudentsCSV.as_view()),
    path('admin/', admin.site.urls),
    path('group/<int:pk>/', core_view.GroupDetailView.as_view(), name='group_detail'),
    path('group/create/', core_view.CreateGroupView.as_view(), name='group_create'),
    path('group/update/<int:pk>/', core_view.UpdateGroupView.as_view(), name='group_update'),
    path('teacher/', core_view.TeacherView.as_view(), name='teacher_all'),
    path('teacher/<int:pk>/', core_view.TeacherDetailView.as_view(), name='teacher_detail'),
    path('teacher/create/', core_view.CreateTeacherView.as_view(), name='teacher_create'),
    path('teacher/update/<int:pk>/', core_view.UpdateTeacherView.as_view(), name='teacher_update'),
    path('student/', core_view.StudentView.as_view(), name='student_all'),
    path('student/create/', core_view.CreateStudentView.as_view(), name='student_create'),
    path('student/update/<int:pk>/', core_view.UpdateStudentView.as_view(), name='student_update'),
    path('student/delete/<int:pk>/', core_view.DeleteStudentView.as_view(), name='student_delete'),
    path('contact_us/', core_view.ContactUsView.as_view(), name='contact_us'),
    path('contact_us/done/', TemplateView.as_view(template_name='contact_us_done.html'), name='contact_us_done'),

    path('__debug__/', include(debug_toolbar.urls)),

    # path('api-auth/', include('rest_framework.urls')),
    path('api/get_token/', obtain_auth_token, name='api_get_token'),
    path('api/students/', api_view.StudentView.as_view({'get': 'list',
                                                        'post': 'create'})),
    path('api/students/<int:pk>/', api_view.StudentView.as_view({'put': 'update'})),
    path('api/groups/', api_view.GroupView.as_view({'get': 'list',
                                                    'post': 'create'})),
    path('api/groups/<int:pk>/', api_view.GroupView.as_view({'get': 'retrieve',
                                                             'put': 'update',
                                                             'delete': 'destroy'})),
    path('api/teachers/', api_view.GroupView.as_view({'get': 'list',
                                                      'post': 'create'})),
    path('api/teachers/<int:pk>/', api_view.GroupView.as_view({'get': 'retrieve',
                                                               'put': 'update',
                                                               'delete': 'destroy'})),
]

lesson6_home_work/core/models.py
from django.db import models
from django.utils import timezone



class Student(models.Model):
    name = models.CharField(max_length=255)
    date_of_birth = models.DateField()

    @property
    def age(self):
        today = timezone.now().date()
        dob = self.date_of_birth
        return today.year - dob.year - (today < dob.replace(year=today.year))

    def __str__(self):
        return self.name


class Teacher(models.Model):
    name = models.CharField(max_length=255)
    email = models.EmailField()

    def __str__(self):
        return self.name


class Group(models.Model):
    name = models.CharField(max_length=255)
    teacher = models.ForeignKey(Teacher, on_delete=models.CASCADE)
    students = models.ManyToManyField(Student)

    @property
    def get_statistic(self):
        ages = [s.age for s in self.students.all()]
        if not ages:
            return {'student_count': 0}
        return {'max_age': max(ages),
                'min_age': min(ages),
                'avg_age': sum(ages) // len(ages),
                'student_count': len(ages),
                }

    def __str__(self):
        return self.name


class Logger(models.Model):
    created = models.DateTimeField()
    request_execution_time = models.FloatField()
    request_method = models.CharField(max_length=255)
    request_path = models.CharField(max_length=255)

    class Meta:
        verbose_name = 'logs'
        verbose_name_plural = 'logs'

    def __str__(self):
        return f'[{self.created.strftime("%d/%m/%Y %H:%M:%S")}] "{self.request_method} {self.request_path}"'


class ExchangeRate(models.Model):
    USD = 840
    EUR = 978
    RUB = 643
    CURRENCY_CHOICE = (
        (USD, 'USD'),
        (EUR, 'EUR'),
        (RUB, 'RUB')
    )
    currency = models.SmallIntegerField(choices=CURRENCY_CHOICE, null=False)
    buy = models.DecimalField(max_digits=8, decimal_places=4, null=False)
    sale = models.DecimalField(max_digits=8, decimal_places=4, null=False)
    created = models.DateTimeField(auto_now_add=True)
    source = models.CharField(max_length=255, null=False)

    def __str__(self):
        return f'{self.get_currency_display()} - ({self.buy}; {self.sale})' \
               f'[{self.created.strftime("%d/%m/%Y %H:%M:%S")}]"{self.source}"'

lesson6_home_work/core/forms.py
from django import forms

from core.models import Teacher, Student, Group
from core.tasks import send_contact_us_email


class GroupForm(forms.ModelForm):
    class Meta:
        model = Group
        fields = '__all__'


class TeacherForm(forms.ModelForm):
    class Meta:
        model = Teacher
        fields = '__all__'


class StudentForm(forms.ModelForm):
    class Meta:
        model = Student
        fields = '__all__'


class ContactUsForm(forms.Form):
    name = forms.CharField(max_length=255)
    email = forms.EmailField()
    message = forms.CharField(
        widget=forms.widgets.Textarea(attrs={})
    )

    def save(self):
        send_contact_us_email.delay(**self.cleaned_data)

lesson6_home_work/core/views.py
from django.db.models import F
from django.http import HttpResponse
from django.shortcuts import render
from django.views.generic import DetailView, CreateView, DeleteView, UpdateView, FormView, View
from django.views.generic.list import ListView
from django.urls import reverse_lazy
import csv
from django.conf import settings
from os import listdir as os_listdir

from core.forms import GroupForm, TeacherForm, StudentForm, ContactUsForm
from core.models import Group, Teacher, Student


class IndexView(ListView):
    template_name = "index.html"
    queryset = Group.objects.get_queryset().\
        prefetch_related('students').\
        annotate(teacher_name=F('teacher__name'))

    # def get_queryset(self):
    #     return Group.objects.get_queryset(
    #     ).prefetch_related('students').annotate(
    #         teacher_name=F('teacher__name'),
    #     )


class TeacherView(ListView):
    template_name = "teacher.html"
    model = Teacher


class StudentView(ListView):
    template_name = "student.html"

    def get_queryset(self):
        return Student.objects.order_by('-id')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        img_path = '/core/images/students_photo/'
        img_names = os_listdir(str(settings.STATIC_ROOT) + img_path)
        context['list_img_path'] = [img_path + name for name in img_names]
        return context



class GroupDetailView(DetailView):
    template_name = 'detail_group.html'
    queryset = Group.objects.get_queryset().\
        select_related('teacher').\
        prefetch_related('students')



class TeacherDetailView(DetailView):
    template_name = 'detail_teacher.html'
    model = Teacher


class MyCreateView(CreateView):
    success_url = reverse_lazy('index')
    template_name = 'create_update.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['button_name'] = 'Create'
        return context


class MyUpdateView(UpdateView):
    template_name = 'create_update.html'
    success_url = reverse_lazy('index')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['button_name'] = 'Update'
        return context


class CreateGroupView(MyCreateView):
    model = Group
    form_class = GroupForm


class CreateTeacherView(MyCreateView):
    model = Teacher
    form_class = TeacherForm


class CreateStudentView(MyCreateView):
    model = Student
    form_class = StudentForm

    def get_template_names(self):
        if self.request.is_ajax():
            return ['includes/short_student_create.html']
        return [self.template_name]

    def form_valid(self, form):
        if self.request.is_ajax():
            form.save()
            context = {'object_list': Student.objects.order_by('-id')}
            return render(template_name=['includes/short_student_data_table.html'], context=context, request=self.request)
        else:
            super(CreateStudentView, self).form_valid(form)


class UpdateGroupView(MyUpdateView):
    model = Group
    form_class = GroupForm


class UpdateTeacherView(MyUpdateView):
    model = Teacher
    form_class = TeacherForm


class UpdateStudentView(MyUpdateView):
    model = Student
    form_class = StudentForm

    def get_template_names(self):
        if self.request.is_ajax():
            # print(dir(self.request))
            return ['includes/short_student_update.html']
        return [self.template_name]

    def form_valid(self, form):
        if self.request.is_ajax():
            form.save()
            context = {'object_list': Student.objects.order_by('-id')}
            return render(template_name=['includes/short_student_data_table.html'], context=context, request=self.request)
        else:
            super(UpdateStudentView, self).form_valid(form)


class DeleteStudentView(DeleteView):
    model = Student
    success_url = reverse_lazy('index')
    template_name = 'delete.html'

    def get_template_names(self):
        if self.request.is_ajax():
            return ['includes/short_student_delete.html']
        return [self.template_name]

    def delete(self, request, *args, **kwargs):
        print(request)
        if self.request.is_ajax():
            self.get_object().delete()
            context = {'object_list': Student.objects.order_by('-id')}
            return render(template_name=['includes/short_student_data_table.html'], context=context, request=self.request)
        else:
            return super().delete(request, *args, **kwargs)


class ContactUsView(FormView):
    template_name = 'contact_us.html'
    success_url = reverse_lazy('contact_us_done')
    form_class = ContactUsForm

    def form_valid(self, form):
        form.save()
        return super(ContactUsView, self).form_valid(form)


class StudentsCSV(View):

    def get(self, request):
        response = HttpResponse(content_type='text/csv')
        response['Content-Disposition'] = 'attachment; filename="students.csv"'
        writer = csv.writer(response)
        writer.writerow([field.name for field in Student._meta.fields])
        writer.writerows(Student.objects.all().values_list())
        return response

lesson6_home_work/core/templates/base.html
{% load bootstrap_tags %}
{% load core_tags %}
{% load static %}
<html>
    <head>
        {% block css %}{% endblock css %}

        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
        <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-Piv4xVNRyMGpqkS2by6br4gNJ7DXjqk09RmUpJ8jgGtD7zP9yug3goQfGII0yAns" crossorigin="anonymous"></script>

        {% block js %}{% endblock js %}
        {% block meta %}{% endblock meta %}
    </head>
    <body>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
          <a class="navbar-brand" href="/">Navbar</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'index' %}">Home <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
{#                    <a class="nav-link" href="{% url 'add_product' %}">Add product</a>#}
                </li>

              <div class="btn-group">
                <button style="background: #343a40; border-color: #343a40;" type="button" class="btn btn-secondary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Random teachers</button>
                <div class="dropdown-menu" x-placement="bottom-start" style="position: absolute; transform: translate3d(0px, 38px, 0px); top: 0px; left: 0px; will-change: transform;">
                    {% random_teachers %}
                </div>
              </div>
              <div class="btn-group">
                <button style="background: #343a40; border-color: #343a40;" type="button" class="btn btn-secondary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Create</button>
                <div class="dropdown-menu" x-placement="bottom-start" style="position: absolute; transform: translate3d(0px, 38px, 0px); top: 0px; left: 0px; will-change: transform;">
                    <a class="dropdown-item" href="{% url 'group_create' %}">Create group</a>
                    <a class="dropdown-item" href="{% url 'teacher_create' %}">Create teacher</a>
                    <a class="dropdown-item" href="{% url 'student_create' %}">Create student</a>
                </div>
              </div>
            </ul>

            <!--<form class="form-inline my-2 my-lg-0">-->
              <!--<input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">-->
              <!--<button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>-->
            <!--</form>-->
            <ul class="navbar-nav my-2">
              <li class="nav-item active">
                <a class="nav-link" href="/" data-toggle="modal" data-target="#login-modal">Login</a>
              </li>
            </ul>
          </div>
        </nav>
        <div class="container">
            {% block content %}
            {% endblock content %}
        </div>
        <div class="modal" tabindex="-1" id="login-modal">
          <div class="modal-dialog">
            <div class="modal-content">
              <div class="modal-header">
                <h5 class="modal-title">Modal title</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button>
              </div>
              <form action="login" method="post">{% csrf_token %}
                  <div class="modal-body">
{#                    {{ login_form|as_bootstrap_horizontal }}#}
                  </div>
                  <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-primary">Save changes</button>
                  </div>
              </form>
            </div>
          </div>
        </div>
    </body>
</html>

lesson6_home_work/core/templates/contact_us.html
{% extends "base.html" %}
{% load bootstrap_tags %}

{% block content %}
    <br>
        <h3>Contact us</h3>
        <div class="container">
            <form method="post" enctype="multipart/form-data" novalidate>{% csrf_token %}
                {{ form|as_bootstrap_horizontal }}
                <button type="submit" class="btn btn-primary">Send</button>
            </form>
        </div>
{% endblock content %}

lesson6_home_work/core/templates/contact_us_done.html
{% extends "base.html" %}

{% block content %}
    <br>
    <h2 class="text-center">email sent</h2>

{% endblock content %}

lesson6_home_work/core/templates/create_update.html
{% extends "base.html" %}
{% load bootstrap_tags %}
{% load core_tags %}

{% block content %}
    <br>
        <div class="container">
            <form method="post" enctype="multipart/form-data" novalidate>{% csrf_token %}
{#                {{ form|as_bootstrap_horizontal }}#}
                <button type="submit" class="btn btn-primary">{{ button_name }}</button>
            </form>
        </div>
{% endblock content %}

lesson6_home_work/core/templates/delete.html
{% extends "base.html" %}
{% load core_tags %}

{% block content %}
    <br>
    <form class="form-actions" method="post">{% csrf_token %}
        <p>Are you sure you want to delete "{{ object }}"?</p>
        <p>
            <button type="button" class="btn btn-primary">Cancel</button>
            <button type="submit" class="btn btn-danger">Delete</button>
        </p>
    </form>
{% endblock content %}

lesson6_home_work/core/templates/detail_group.html
{% extends "base.html" %}
{% load core_tags %}

{% block content %}
        <div class="container"><br>
            <div class="card col-md-12">
              <div class="card-body">
                <h5 class="card-title">Group: {{ group.name }}</h5>
                <p class="card-text">Teacher: {{ group.teacher }}</p>
                <p>Students:</p>
                  {% for student in group.students.all %}
                    {{ student.name }}
                    <br>
                  {% endfor %}
              </div>
            </div><br>
        </div>
{% endblock content %}

lesson6_home_work/core/templates/detail_teacher.html
{% extends "base.html" %}
{% load core_tags %}

{% block content %}
        <div class="container"><br>
            <div class="card col-md-12">
              <div class="card-body">
                <h5 class="card-title">Teacher: {{ teacher.name }}</h5>
                <p class="card-text">email: {{ teacher.email }}</p>
                <p>Groups:</p>
                  {% for group in teacher.group_set.all%}
                    {{ group.name }}
                  {% endfor %}
              </div>
            </div><br>
        </div>
{% endblock content %}

lesson6_home_work/core/templates/index.html
{% extends "base.html" %}
{% load core_tags %}

{% block content %}
        {% for group in object_list %}
            <div class="container"><br>
                <div class="card col-md-12">
                  <div class="card-body">
                    <h4 class="card-title"><a href="{% url 'group_detail' group.id %}">{{ group.name }}</a></h4>
                    <p class="card-text"><a href="{% url 'teacher_detail' group.teacher_id %}">{{ group.teacher_name }}</a></p>
                    {% with group.get_statistic as statistic %}
                        <p class="card-text">Number of students: {{ statistic.student_count }}</p>
                        <p class="card-text">Maximum age of students: {{ statistic.max_age }}</p>
                        <p class="card-text">Minimum age of students: {{ statistic.min_age }}</p>
                        <p class="card-text">Average age of students: {{ statistic.avg_age }}</p>
                    {% endwith %}
                  </div>
                </div><br>
            </div>
        {% endfor %}
{% endblock content %}

lesson6_home_work/core/templates/student.html
{% extends "base.html" %}
{% load core_tags %}
{% load static %}

{% block css %}
    <link rel="stylesheet" type="text/css" href="{% static "core/css/student.css" %}">
{% endblock css %}

{% block js %}
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script src="{% static "core/js/student_crud.js" %}"></script>
    <script src="{% static "core/js/carousel.js" %}"></script>
{% endblock js %}


{% block content %}
    <br>
    <div class="carousel row" >
        <button class="img_prev btn btn-primary column left" type="button">Prev</button>
        <div class="img_set column middle">
            {% for path in list_img_path %}
                <img class="student_image" src="{% static path %}" style="display: none;">
            {% endfor %}
        </div>
        <button class="img_next btn btn-primary column right" type="button">Next</button>
    </div>
    <br>
    <h3 align="center">All students</h3>
    <br>
    <div id="add_student" class="table">
        <button class="add_button btn btn-primary" type="button"> + Add student</button>
    </div>
    <div class="delete_student_modal"></div>
    <table class="table" id="data-table" style="width: 100%">
        <colgroup>
            <col span="1" style="width: 5%;">
            <col span="1" style="width: 30%;">
            <col span="1" style="width: 30%;">
            <col span="1" style="width: 5%;">
            <col span="1" style="width: 30%;">
        </colgroup>
        <tr>
            <th>ID</th>
            <th>Name</th>
            <th>Date of birth</th>
            <th>Age</th>
            <th>Action</th>
        </tr>
        {% for student in object_list %}
            <tbody class="student">
                <tr class="update_form" style="display: none; background-color: {% cycle "lightgrey" "white" %}"></tr>
                <tr class="student_row" style="background-color: {% cycle "lightgrey" "white" %}">
                    <td class="student_id">{{ student.id }}</td>
                    <td>{{ student.name }}</td>
                    <td>{{ student.date_of_birth }}</td>
                    <td>{{ student.age }}</td>
                    <td>
                        <button class="update btn btn-primary" type="button">Edit</button>
                    </td>
                </tr>
            </tbody>
        {%  endfor %}
    </table>
{% endblock content %}

lesson6_home_work/core/templates/teacher.html
{% extends "base.html" %}
{% load core_tags %}

{% block content %}
        {% for teacher in object_list %}
        <div class="container"><br>
            <div class="card col-md-12">
              <div class="card-body">
                <h4 class="card-title"><a href="{% url 'teacher_detail' teacher.id %}">{{ teacher.name }}</a></h4>
                <p class="card-text">{{ teacher.email }}</p>
              </div>
            </div><br>
        </div>
        {% endfor %}
{% endblock content %}